### ISSUE TITLE
Trying to read non-existent sampled_knots file

### ISSUE THREAD

**Issue by linxichen** [MarkBlyth/BarsNWrapper#1]
Tried to run on some data, but got this error 

FileNotFoundError: [Errno 2] No such file or directory: 'sampled_knots_200824_235042'

**Comment by MarkBlyth** [comment]
The sampled knots file is created by the BarsN executable after successful completion. The FileNotFoundError means the executable hasn't created the file as expected, for some reason. Did the executable compile properly? It's written for some outdated compiler standards, so I had to edit the makefile to get it to compile; perhaps that's where the issue lies?

Otherwise, if the compilation is fine, the issue will be something going wrong when BarsN.out is executed. What messages are sent to the terminal when your code runs, before the exception is raised?

**Comment by linxichen** [comment]
> The sampled knots file is created by the BarsN executable after successful completion. The FileNotFoundError means the executable hasn't created the file as expected, for some reason. Did the executable compile properly? It's written for some outdated compiler standards, so I had to edit the makefile to get it to compile; perhaps that's where the issue lies?
> 
> Otherwise, if the compilation is fine, the issue will be something going wrong when BarsN.out is executed. What messages are sent to the terminal when your code runs, before the exception is raised?

Hi Mark,

The executable compiles and actually runs fine, but it seems like by default BarsN.out doesn't generate sampled_knots file (when I only put the executable in the same path as the python wrapper, without specifying any param file)

**Comment by MarkBlyth** [comment]
The wrapper expects the executable to be at ./BarsNWrapper/barsN.out, so try moving wrapper.py into your working directory, and placing the executable in a BarsNWrapper subdirectory. Alternatively, you can put the executable somewhere more convenient and change line 8 of wrapper.py to reflect where it is. That should solve the problem.

**Comment by hao199509** [comment]
Hello Mark,
I faced the same issue with lixinchen,i have read what you said above,did you mean i have to make an ececutable BarsN.out file by makefile GCC using barsN.c?

**Comment by hao199509** [comment]
> 

hi Linxi, did you deal with that issue "No such file or directory: 'sampled_knots_220829_185142",if yes,could you please teach me how to deal with?

**Comment by linxichen** [comment]
Hi Hao, I did solve the issue but forgot the details. Sorry

**Comment by hao199509** [comment]
nothing wrong，thanks for replying my issue


发自我的iPhone

------------------ Original ------------------
From: linxichen ***@***.***&gt;
Date: 周日,9月 11,2022 10:33 下午
To: MarkBlyth/BarsNWrapper ***@***.***&gt;
Cc: hao199509 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [MarkBlyth/BarsNWrapper] Trying to read non-existentsampled_knots file (#1)





 
Hi Hao, I did solve the issue but forgot the details. Sorry

**Comment by linxichen** [comment]
Issues resolved by manually changing the files to point to.
